name: test

on:
  - push

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo search --limit 1 cargo-edit 2> /dev/null | head -n1 | cut -d' ' -f3 | cut -d'"' -f2
      - run: |
          cargo install cargo-edit
      - run: |
          $HOME/.cargo/bin/cargo-set-version -V
      - run: |
          cargo search --limit 1 cargo-edit | head -n1 | cut -d' ' -f3 | cut -d'"' -f2
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: |
          ./target/release/pr_rust
