name: test

on:
  - push

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - id: cargo-edit
        shell: bash
        run: |
          echo "::set-output name=version::$(cargo search --limit 1 cargo-edit 2> /dev/null | head -n1 | cut -d' ' -f3 | cut -d'"' -f2)"

      - name: Cache cargo-edit
        id: cache-cargo
        uses: actions/cache@v2
        with:
          path: $HOME/.cargo/bin/
          key: v2-${{ runner.os }}-${{ steps.cargo-edit.outputs.version }}

      - name: cargo-edit
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: |
          cargo install cargo-edit
      - run: |
          $HOME/.cargo/bin/cargo-set-version -V
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: |
          ./target/release/pr_rust
