name: test

on:
  - push

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo install cargo-edit
      - run: |
          find ~
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: |
          ./target/release/pr_rust
